version: "3.8"
services:
  dev-postgres:
    image: postgres:14.4-alpine
    hostname: dev-postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - backend
  backend-nestjs:
    build:
      context: ./backend
    hostname: backend-nestjs
    tty: true
    ports:
      - "3001:3001"
      - "5555:5555"
    networks:
      - backend
    depends_on:
      - dev-postgres
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
  frontend-nextjs:
    build:
      context: ./frontend
    tty: true
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - dev-postgres
      - backend-nestjs
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
networks:
  backend:
